# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 219f42ae01d1d7fdd3724c30388d6998ad9d97fd944fe8b3242b156cee5355fd32c5891cdd9faba83b6c586e69d3605c0053010783c243b4524d06592c1e9c3f

test:
  secret_key_base: 85324ba38d7fad8e643f0fffee2d45d677672b6daeb6141083a36a508b71768888c4ffa333360f868102ac4475454b4a6de08770fe790e38411429243109718b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
